name: CI

on:
  push:
    branches:
      - main
  pull_request: ~
  workflow_dispatch: ~

jobs:
  tests:
    name: Tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build and load Docker images
        uses: docker/bake-action@v4
        with:
          load: true
          files: |
            docker-compose.yml
          set: |
            *.cache-from=type=gha,scope=${{ github.ref }}
            *.cache-to=type=gha,scope=${{ github.ref }},mode=max

      - name: Start services
        run: docker compose up -d --wait

      - name: Install dependencies
        run: docker compose exec -T php composer install

      - name: Run PHPUnit
        run: docker compose exec -T php vendor/bin/phpunit

      - name: Run Pint
        run: docker compose exec -T php vendor/bin/pint --test

  lint:
    name: Docker Lint
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Lint Dockerfile
        uses: hadolint/hadolint-action@v3.1.0